### ISSUE TITLE
train_forecast.py error

### ISSUE THREAD

**Issue by JIANGYUE61610306** [KL4805/TransGTR#1]
I faced below error when loading the parameters for train_forecast.py.

File "/home/jiangyue/anaconda3/envs/transfer/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TSFormer:
        Unexpected key(s) in state_dict: "diw_embedding", "encoder.transformer_encoder.layers.3.self_attn.in_proj_weight", "encoder.transformer_encoder.layers.3.self_attn.in_proj_bias", "encoder.transformer_encoder.layers.3.self_attn.out_proj.weight", "encoder.transformer_encoder.layers.3.self_attn.out_proj.bias", "encoder.transformer_encoder.layers.3.linear1.weight", "encoder.transformer_encoder.layers.3.linear1.bias", "encoder.transformer_encoder.layers.3.linear2.weight", "encoder.transformer_encoder.layers.3.linear2.bias", "encoder.transformer_encoder.layers.3.norm1.weight", "encoder.transformer_encoder.layers.3.norm1.bias", "encoder.transformer_encoder.layers.3.norm2.weight", "encoder.transformer_encoder.layers.3.norm2.bias". 

After solved by change engine.py line 250 to self.tsformer.load_state_dict(sd, strict=False), I face another error as below:

raining forecast model, transfer from METR-LA to PEMSD7M, with 0 day target data
Traceback (most recent call last):
  File "/home/jiangyue/github/TransGTR/train_forecast.py", line 312, in <module>
    main(args)
  File "/home/jiangyue/github/TransGTR/train_forecast.py", line 146, in main
    metrics = engine.source_train(xs, ys, long_xs, xt, yt)
  File "/home/jiangyue/github/TransGTR/engine.py", line 283, in source_train
    out, tonly_s, st_s = self.gwnet_model(xs[:,:,:,:2], adp=None, sampled_adj=sampled_adj, return_st=True)
  File "/home/jiangyue/anaconda3/envs/transfer/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jiangyue/anaconda3/envs/transfer/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jiangyue/github/TransGTR/model.py", line 762, in forward
    gate = self.gate_convs[i](residual)
  File "/home/jiangyue/anaconda3/envs/transfer/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jiangyue/anaconda3/envs/transfer/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jiangyue/anaconda3/envs/transfer/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/jiangyue/anaconda3/envs/transfer/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [64, 32, 207, 13]

**Comment by KL4805** [comment]
Please also give me the full script you use, otherwise I cannot replicate it and further see what is wrong.

**Comment by JIANGYUE61610306** [comment]
I downgraded PyTorch version and solved above error, thanks!

**Comment by JIANGYUE61610306** [comment]
Thanks
